strace_0: 0-strace.o
	gcc -Wall -Werror -Wextra -pedantic 0-strace.o -o strace_0
strace_1: 1-strace.o
	gcc -Wall -Werror -Wextra -pedantic 1-strace.o -o strace_1
0-strace.o: 0-strace.c 
1-strace.o: 1-strace.c
