strace_0: 0-strace.o
	gcc -Wall -Werror -Wextra -pedantic 0-strace.o -o strace_0
strace_1: 1-strace.o
	gcc -Wall -Werror -Wextra -pedantic 1-strace.o -o strace_1
strace_2: 2-strace.o
	gcc -Wall -Werror -Wextra -pedantic 2-strace.o -o strace_2
strace_3: 3-strace.o
	gcc -Wall -Werror -Wextra -pedantic 3-strace.o -o strace_3
0-strace.o: 0-strace.c 
1-strace.o: 1-strace.c
2-strace.o: 2-strace.c
3-strace.o: 3-strace.c
