0-hreadelf:
	gcc -Wall -Werror -Wextra -pedantic read_pipe.c -o 0-hreadelf
1-hreadelf:
	gcc -Wall -Werror -Wextra -pedantic read_pipe_elf_sections.c -o 1-hreadelf
2-hreadelf:
	gcc -Wall -Werror -Wextra -pedantic read_pipe_elf_prhdrs.c -o 2-hreadelf
		
